/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventarislabgui.view;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import com.mycompany.inventarislabgui.model.Alat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author muhammadyoga
 */
public class AlatView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlatView.class.getName());

    /**
     * Creates new form AlatView
     */
    public AlatView() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public String getKode() {
        return txtKode.getText().trim();
    }

    public String getNama() {
        return txtNama.getText().trim();
    }

    public String getJumlah() {
        return txtJumlah.getText().trim();
    }

    public String getKondisi() {
        return (String) cmbKondisi.getSelectedItem();
    }
    
    public int getBarisTerpilih() {
        return tblAlat.getSelectedRow();
    }

    //Pemasangan listener (dipanggil oleh Controller
    public void addTambahListener(ActionListener listener) {
        btnTambah.addActionListener(listener);
    }
    
    public void addUbahListener(ActionListener listener) {
        btnUbah.addActionListener(listener);
    }

    public void addPilihBarisListener(ListSelectionListener listener) {
        tblAlat.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                listener.valueChanged(e);
            }
        });
    }
     
    public void addHapusListener(ActionListener listener) {
        btnHapus.addActionListener(listener);
    }
     
    public void addBersihkanListener(ActionListener listener) {
        btnBersihkan.addActionListener(listener);
    }

    //Output ke pengguna
    public void kosongkanForm() {
        txtKode.setText("");
        txtNama.setText("");
        txtJumlah.setText("");
        cmbKondisi.setSelectedIndex(0);
        txtKode.setEditable(true);
        tblAlat.clearSelection();
    }
    
    public void tampilkanData(List<Alat> daftarAlat) {
        DefaultTableModel model = (DefaultTableModel) tblAlat.getModel();
        model.setRowCount(0);
        for (Alat alat : daftarAlat) {
            model.addRow(new Object[]{
                alat.getKode(), alat.getNama(), alat.getJumlah(), alat.getKondisi()
            });
        }
    }
    
    public void isiForm(Alat alat) {
        txtKode.setText(alat.getKode());
        txtNama.setText(alat.getNama());
        txtJumlah.setText(String.valueOf(alat.getJumlah()));
        cmbKondisi.setSelectedItem(alat.getKondisi());
        txtKode.setEditable(false);
    }
    
    public boolean konfirmasi(String pesan) {
        int pilihan = JOptionPane.showConfirmDialog(this, pesan, "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        return pilihan == JOptionPane.YES_OPTION;
    }
    
    //Info Dialog
    public void tampilkanInfo(String pesan) {
        JOptionPane.showMessageDialog(this, pesan, "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
    }

    public void tampilkanPeringatan(String pesan) {
        JOptionPane.showMessageDialog(this, pesan, "Peringatan",
                JOptionPane.WARNING_MESSAGE);
    }

    public void tampilkanError(String pesan) {
        JOptionPane.showMessageDialog(this, pesan, "Kesalahan Database",
                JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulAplikasi = new javax.swing.JLabel();
        lblKode = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        lblKondisi = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        cmbKondisi = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBersihkan = new javax.swing.JButton();
        scrAlat = new javax.swing.JScrollPane();
        tblAlat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventaris Alat");

        lblJudulAplikasi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudulAplikasi.setText("Inventaris Alat Laboratorium");

        lblKode.setText("Kode Alat:");

        lblNama.setText("Nama Alat:");

        lblJumlah.setText("Jumlah:");

        lblKondisi.setText("Kondisi:");

        cmbKondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Rusak Ringan", "Rusak Berat" }));

        btnTambah.setText("Tambah");

        btnUbah.setText("Ubah");

        btnHapus.setText("Hapus");

        btnBersihkan.setText("Bersihkan");

        tblAlat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama Alat", "Jumlah", "Kondisi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlat.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrAlat.setViewportView(tblAlat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBersihkan))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJudulAplikasi)
                            .addComponent(scrAlat)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNama)
                                    .addComponent(lblKode))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKode, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                    .addComponent(txtNama)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJumlah)
                                    .addComponent(lblKondisi))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJumlah))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulAplikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKode)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlah)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKondisi)
                    .addComponent(cmbKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnBersihkan))
                .addGap(18, 18, 18)
                .addComponent(scrAlat)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new AlatView().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbKondisi;
    private javax.swing.JLabel lblJudulAplikasi;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblKondisi;
    private javax.swing.JLabel lblNama;
    private javax.swing.JScrollPane scrAlat;
    private javax.swing.JTable tblAlat;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
